
---
- name: Task 1 - Archive, Tuned and MOTD
  hosts: webservers
  become: yes
  vars:
    my_greeting: "Welcome to my managed server!"
    kafka_url: "https://archive.apache.org/dist/kafka/3.6.1/kafka_2.13-3.6.1.tgz"
    dest_dir: "/tmp/kafka_extracted"

  tasks:
    # --- БЛОК 1.1: РАБОТА С АРХИВОМ ---
    - name: Создайте каталог для распаковки
      file:
        path: "{{ dest_dir }}"
        state: directory
        mode: '0755'

    - name: УСТАНОВКА kafka 
      unarchive:
        src: "{{ kafka_url }}"
        dest: "{{ dest_dir }}"
        remote_src: yes  # Скачивание напрямую на целевой сервер

    # --- БЛОК 1.2: УСТАНОВКА И ЗАПУСК TUNED ---
    - name: УСТАНОВКА И ЗАПУСК TUNED
      apt:
        name: tuned
        state: present
        update_cache: yes

    - name: функция tuned запущена и включена
      service:
        name: tuned
        state: started
        enabled: yes

    # --- БЛОК 1.3: НАСТРОЙКА ПРИВЕТСТВИЯ (MOTD) ---
    
    - name: Установка динамического ПРИВЕТСТВИЯ
      copy:
        content: |
          Welcome to server {{ ansible_hostname }}!
          Your IP address is {{ ansible_default_ipv4.address }}.
          Have a great day, System Administrator!
        dest: /etc/motd